### ISSUE TITLE
Does not work on Kitty ≥0.21.0

### ISSUE THREAD

**Issue by AckslD** [yurikhan/kitty_grab#12]
When running I'm getting the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 136, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 127, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 84, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 71, in run_kitten
    rk(kitten)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 124, in run_kitten
    m = runpy.run_path(path, init_globals={'sys': sys, 'os': os}, run_name='__run_kitten__')
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/axel/.config/kitty/kitty_grab/grab.py", line 3, in <module>
    import _grab_ui
ModuleNotFoundError: No module named '_grab_ui'  
```
even though `_grab_ui.py` is in that folder. Any idea why?

**Comment by yurikhan** [comment]
What is your OS and Kitty versions, so I could possibly try reproducing this?

Also, at the top of `grab.py`, please add these lines:

```python
import sys
raise Exception(f'{sys.path!r}')
```
and tell me what it thinks its module search path is.

**Comment by AckslD** [comment]
@yurikhan Sorry, should have included this information when opening the issue:

OS: 5.12.11.arch1-1
kitty: 0.21.1
kitty_grab: ba283a4

Output from the above exception:
```
Traceback (most recent call last):
  File "/home/axel/.config/kitty/kitty_grab/grab.py", line 3, in <module>
    raise Exception(f'{sys.path!r}')
Exception: ['/home/axel/.config/kitty/kitty_grab', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/axel/.local/lib/python3.9/site-packages', '/home/axel/Dev/manven', '/usr/lib/python3.9/site-packages'] 
```

**Comment by yurikhan** [comment]
Hm. I don’t really know, it should be able to import `_grab_ui` given that path.

That said, the only reason the module is imported is to take its full file name in this line:

```
    boss._run_kitten(_grab_ui.__file__, args=[
```

That, in turn, is a hack against the fact that `__file__` is not set in the global environment of the kitten. Could you please check, maybe that had been fixed in the mean time?

```
raise Exception(f'__file__ is {__file__}')
```

Anyway, until I resolve the issue, you should be able to restore functionality by removing `import _grab_ui` and replacing `_grab_ui.__file__` with `'/home/axel/.config/kitty/kitty_grab/_grab_ui.py'`. (This hardcodes your path into the code so it will not play nice with dotfiles synchronization between machines.)

**Comment by AckslD** [comment]
It seems like `__file__` is correctly set so could be used instead. I opened a PR that does this, see #13 

So I don't have the exception anymore but now nothing happens if I press the keys I have bound to the kitten. Can I get some logging in some way to see what's going on?

**Comment by yurikhan** [comment]
If you start `kitty` from another terminal, or even from another instance of `kitty`, any errors happening in `_grab_ui.py` will be displayed. (In fact I had thought this was how you got the original traceback in this issue.)

Also, are you certain nothing happens? The normal behavior of the grabber is to re-paint the current screen image, position the cursor at the same point it was when you invoked the kitten, and change the window title.

Or do you mean it enters the grabbing mode, and then none of the keys that are supposed to move the cursor work? I guess that may happen, because Kitty 0.21 implements a whole new keyboard reporting format, which might have broken key handling.

I’m currently on Kitty 0.17.4 and not really in the shape to upgrade right now, sorry. If you find an easy solution, or, alternatively, that the solution is not easy, I’d appreciate if you dropped me a note.

**Comment by AckslD** [comment]
@yurikhan Scratch everything I said before, I was checking the errors wrong, the actual error is
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 694, in dispatch_possible_special_key
    return self.dispatch_action(key_action)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 765, in dispatch_action
    passthrough = f(*key_action.args)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1011, in kitten
    self._run_kitten(kitten, kargs)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 944, in _run_kitten
    end_kitten = create_kitten_handler(kitten, orig_args)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 58, in create_kitten_handler
    m = import_kitten_main_module(config_dir, kitten)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 44, in import_kitten_main_module
    exec(code, g)
  File "/home/axel/.config/kitty/kitty_grab/grab.py", line 3, in <module>
    import _grab_ui
  File "/home/axel/.config/kitty/kitty_grab/_grab_ui.py", line 13, in <module>
    from kitty.conf.definition import (               # type: ignore
ModuleNotFoundError: No module named 'kitty.conf.definition'
```
Sorry for the confusion. 

I was trying to look in the changelog of kitty and in issues what happened to this module but couldn't find anything. If I uncomment this line it also fails on the next with:
```
...
  File "/home/axel/.config/kitty/kitty_grab/_grab_ui.py", line 15, in <module>
    from kitty.conf.utils import (                    # type: ignore
ImportError: cannot import name 'init_config' from 'kitty.conf.utils' (/usr/bin/../lib/kitty/kitty/conf/utils.py)
```

So there seem to have been some changes in the library but cannot really find when this happened and what one should use instead.

**Comment by yurikhan** [comment]
Yeah, the API that Kitty exposes to kittens is pretty much all undocumented and subject to change at any time. So it seems things that lived in `kitty.conf.definition` moved to `kitty.conf.types` or `kitty.conf.utils` or disappeared, and someone some day will have to work it out. I will mention that this kitten does not currently work on Kitty 0.21.0 or later.

This is the machinery that parses the grabber’s configuration file, so if you go in and start commenting things out until they stop failing, you’ll end up with your preferences baked into the kitten.

**Comment by AckslD** [comment]
@yurikhan I see! I would like to help but since I haven't worked with the kitten API before I thought I might be faster to first ask the community for some tips than me digging around to find what to use instead, so I wrote a post on r/KittyTerminal [here](https://www.reddit.com/r/KittyTerminal/comments/o46tx0/question_about_kitten_api_changes/).

**Comment by kovidgoyal** [comment]
The entire config parsing machinery was changed in 0.21.0 for greatly improved startup time (the time to deal with setting up the default options object on startup was reduced by an order of magnitude) and to support config live reloading. 

However that means the options system is less flexible/re-useable in third party kittens.  

The way it works in kitty now is that there is an options/definition.py file that defines all options alongwith default values/documentation. This file is large/slow and is not imported at all during normal operations. Then there is a gen-config.py script that uses the definitions file to autogenerate options/types.py ad options/parse.py. These latter two are what are actually imported used in kitty. 

So to port this to your kitten you would need:

1) To write an options/definition.py file
2) Modify gen-config.py to work with third party kittens to generate options/types.py and options/parse.py
3) Modify the config parsing code in your kitten to use the new facilities

I can help with (2) and if you have questions feel free to ask.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/32d275c1381fffaaf8ef348261c1dfacd7a41b24

**Comment by AckslD** [comment]
Thanks a lot @kovidgoyal! :tada:

@yurikhan I started trying to make this work and have written the files `kitten_options_definition.py` and `kitten_options_utils.py`, see the WIP PR #14

@kovidgoyal When running
```
kitty +runpy 'from kitty.conf.generate import main; main()' /path/to/kitten_options_definition.py
```
I get
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 136, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 127, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 84, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 28, in runpy
    exec(args[1])
  File "<string>", line 1, in <module>
  File "/usr/bin/../lib/kitty/kitty/conf/generate.py", line 446, in main
    m = importlib.import_module('kitten_options_definition')
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kitten_options_definition'  
```

Any idea why? I have latest `kitty-git` from AUR installed.

**Comment by kovidgoyal** [comment]
I assume you replaced /path/to/kitten_options_definition.py with an
actual path to the file?

**Comment by AckslD** [comment]
I used a relative path, with absolute path it worked :+1:

**Comment by AckslD** [comment]
@yurikhan @kovidgoyal The option parsing now works but it's not clear to me how to connect the keys to the actions of `kitty_grab`. In the current setup I get:
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 270, in parse_kittens_func_args
    parser = args_funcs[func]
KeyError: 'move'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 136, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 127, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 84, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 28, in runpy
    exec(args[1])
  File "<string>", line 1, in <module>
  File "/usr/bin/../lib/kitty/kitty/conf/generate.py", line 449, in main
    cls, tc = generate_class(defn, loc)
  File "/usr/bin/../lib/kitty/kitty/conf/generate.py", line 277, in generate_class
    for val in func(text):
  File "/home/axel/Dev/config/kitty/kitty_grab/kitten_options_utils.py", line 19, in parse_map
    x = parse_kittens_key(val, args_funcs)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 299, in parse_kittens_key
    ans = parse_kittens_func_args(action, funcs_with_args)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 272, in parse_kittens_func_args
    raise KeyError(
KeyError: 'Unknown action: move. Check if map action: move left is valid'
```

**Comment by kovidgoyal** [comment]
For shortcuts you have to define args_with_funcs and register all the functionsthat take arguments with it in definition.py see the definition.py of the diff kitten for examples.

**Comment by AckslD** [comment]
The generation of the config now works and it generates `kitten_options_parse.py` and `kitten_options_types.py`. When running the kitten however it fails cause:
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 694, in dispatch_possible_special_key
    return self.dispatch_action(key_action)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 765, in dispatch_action
    passthrough = f(*key_action.args)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1013, in kitten
    self._run_kitten(kitten, kargs)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 946, in _run_kitten
    end_kitten = create_kitten_handler(kitten, orig_args)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 67, in create_kitten_handler
    m = import_kitten_main_module(config_dir, kitten)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 55, in import_kitten_main_module
    exec(code, g)
  File "/home/axel/.config/kitty/kitty_grab/grab.py", line 3, in <module>
    import _grab_ui
  File "/home/axel/.config/kitty/kitty_grab/_grab_ui.py", line 13, in <module>
    from .kitten_options_types import (               # type: ignore
ImportError: attempted relative import with no known parent package
```

**Comment by kovidgoyal** [comment]
remove the leading dot on the import.

**Comment by AckslD** [comment]
Thanks @kovidgoyal!

@yurikhan @kovidgoyal After quite some trial and error I finally got it working :tada: There are three remaining questions I have, although that discussion should maybe be brought to the PR:

1. When handling the `action` returned from `shortcut_action` of the `Handler` [here](https://github.com/AckslD/kitty_grab/blob/8f15b64cd2fcadcb65a744ba744f95d790e358dd/_grab_ui.py#L505) the `args` is a tuple of lenght zero or one and if it's of lenght one the args are actually a string separated by space. Not sure why this is but I just instead split the string to get the args.
2. I removed `on_text` since it was not working and don't know what it is supposed to do/
3. How to handle the generated files `kitten_options_parse.py` and `kitten_options_types.py`? What's a good way for the user to build these?

**Comment by kovidgoyal** [comment]
3. the user doesnt build them, generate them once and check them into the source repo. Update if/when you change definition.py

**Comment by AckslD** [comment]
> the user doesnt build them, generate them once and check them into the source repo. Update if/when you change definition.py

I see, thanks!

**Comment by yurikhan** [comment]
1. Will reply later.

2. I thought `on_text` would be involved if binding a single character key, such as `q` to quit, or maybe vim-like hjkl navigation. But if you find such keys work without `on_text`, it’s okay to remove it.

3. I agree with Kovid, we can make an exception here to the usual rule of not storing generated files in VCS, so that a fresh checkout is immediately usable without a build step.

4. I think we’ll bite the bullet here and keep separate branches for <0.21 and ≥0.21.
